name: Update Threat Hunt Report

on:
  issue_comment:
    types: [edited]

permissions:
  issues: read
  contents: write
  pull-requests: write

jobs:
  update-report: 
    runs-on: ubuntu-latest
    env:
      COMMENT_BODY: ${{ github.event.comment.body }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Update Report
      run: |
        # FILE_CONTENT=$(<hunt-reports/hunt-report-2025-08-09-2-this-is-a-test.md)
        FILE_NAME="hunt-reports/hunt-report-2025-08-09-2-this-is-a-test.md"


        echo -e "$COMMENT_BODY"
        echo "wow"
        echo $(<hunt-reports/hunt-report-2025-08-09-2-this-is-a-test.md)
        echo "wow1"

        FIRST_LINE=$(echo "$COMMENT_BODY" | head -n 1)
        LAST_LINE=$(echo "$COMMENT_BODY" | tail -n 1)

        FIRST_LINE=$(echo "$FIRST_LINE" | sed 's/\\//g')
        LAST_LINE=$(echo "$LAST_LINE" | sed 's/\\//g')
        
        printf '%q\n' "$FIRST_LINE" "$LAST_LINE"
        
        # Replace the block between tags

        # echo "$FILE_CONTENT" | sed "s/\($FIRST_LINE.*$LAST_LINE\)/foo/g"
        echo "s/$FIRST_LINE\n.*\n$LAST_LINE/\nfoo\n/g" "$FILE_NAME"
        sed -i "s/$FIRST_LINE\n.*\n$LAST_LINE/\nfoo\n/g" "$FILE_NAME" > what.md

      
    - uses: stefanzweifel/git-auto-commit-action@v6
