name: Update Threat Hunt Report

on:
  issue_comment:
    types: [edited]

permissions:
  issues: read
  contents: write
  pull-requests: write

jobs:
  update-report: 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Update Report
      run: |
        COMMENT_BODY="${{ github.event.comment.body }}"
        FILE="hunt-report-2025-08-09-2-this-is-a-test.md"

        FIRST_LINE=$(echo $COMMENT_BODY | head -n 1)
        LAST_LINE=$(echo $COMMENT_BODY | tail -n 1)
        # CONTENT=$(echo $COMMENT_BODY | head -n -1 | tail -n +2)
        
        # Replace the block between tags
        sed -i 's/($FIRST_LINE).*($LAST_LINE)/($FIRST_LINE) foo ($LAST_LINE)/g' $FILE

    - name: Commit Report
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add hunt-reports/
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update threat hunt report for issue #${{ github.event.issue.number }}: ${{ github.event.issue.title }}"
          git push
        fi
