name: Update Threat Hunt Report

on:
  issue_comment:
    types: [edited]

permissions:
  issues: read
  contents: write
  pull-requests: write

jobs:
  update-report: 
    runs-on: ubuntu-latest
    env:
      COMMENT_BODY: ${{ github.event.comment.body }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Update Report
      run: |
        FILE=$(<hunt-reports/hunt-report-2025-08-09-2-this-is-a-test.md)

        echo -e "$COMMENT_BODY"
        echo "wow"

        FIRST_LINE=$(echo "$COMMENT_BODY" | head -n 1)
        LAST_LINE=$(echo "$COMMENT_BODY" | tail -n 1)

        ESC_FIRST=$(printf '%s\n' "$FIRST_LINE" | sed 's/[.[\*^$(){}+?|/]/\\&/g')
        ESC_LAST=$(printf '%s\n' "$LAST_LINE" | sed 's/[.[\*^$(){}+?|/]/\\&/g')

        
        # Replace the block between tags
        sed -i "s,\"$ESC_FIRST\".*\"$ESC_LAST\",\"$ESC_FIRST\"foo\"$ESC_LAST\",g" $FILE
        # sed -i "/$ESC_FIRST/,/$ESC_LAST/c\\
        # $COMMENT_BODY" "$FILE"

    - uses: stefanzweifel/git-auto-commit-action@v6
