name: Update Threat Hunt Report

on:
  issue_comment:
    types: [edited]

permissions:
  issues: read
  contents: write
  pull-requests: write

jobs:
  update-report: 
    runs-on: ubuntu-latest
    env:
      COMMENT_BODY: ${{ github.event.comment.body }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Update Report
      run: |
        FILE=$(<hunt-report-2025-08-09-2-this-is-a-test.md)

        echo -e "$COMMENT_BODY"
        echo "wow"

        read -r FIRST_LINE _ <<< "$COMMENT_BODY"
        
        echo "$FIRST_LINE"
        echo "first_line above"
        # echo "$LAST_LINE"

        echo "$FILE"
        
        # Replace the block between tags
        # sed -i "s,\"$ESC_FIRST\".*\"$ESC_LAST\",\"$ESC_FIRST\"foo\"$ESC_LAST\",g" $FILE
        # sed -i "/$ESC_FIRST/,/$ESC_LAST/c\\
        # $COMMENT_BODY" "$FILE"

    - uses: stefanzweifel/git-auto-commit-action@v6
