name: Update Threat Hunt Report

on:
  issue_comment:
    types: [edited]

permissions:
  issues: read
  contents: write
  pull-requests: write

jobs:
  update-report: 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Update Report
      run: |
        COMMENT_BODY="${{ github.event.comment.body }}"
        FILE="hunt-reports/hunt-report-2025-08-09-2-this-is-a-test.md"

        FIRST_LINE=$(echo $COMMENT_BODY | head -n 1)
        LAST_LINE=$(echo $COMMENT_BODY | tail -n 1)
        # CONTENT=$(echo $COMMENT_BODY | head -n -1 | tail -n +2)

        # echo "$FIRST_LINE"
        # echo "$LAST_LINE"
        
        # Replace the block between tags
        sed -i 's/("$FIRST_LINE").*("$LAST_LINE")/("$FIRST_LINE")("foo")("$LAST_LINE")/g' $FILE

    - uses: stefanzweifel/git-auto-commit-action@v6
