name: Update Threat Hunt Report

on:
  issue_comment:
    types: [edited]

permissions:
  issues: read
  contents: write
  pull-requests: write

jobs:
  update-report: 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Update Report
      run: |
        COMMENT_BODY="${{ github.event.comment.body }}"
        FILE="hunt-report-2025-08-09-2-this-is-a-test.md"
        
        # Build replacement block safely
        REPLACEMENT=$(printf "%s\n%s\n%s" \
        "<!-- CONCLUSION_TAG_START -->" \
        "$COMMENT_BODY" \
        "<!-- CONCLUSION_TAG_END -->")
        
        # Now do sed replacement
        sed -i "/<!-- CONCLUSION_TAG_START -->/,/<!-- CONCLUSION_TAG_END -->/c$REPLACEMENT" "$FILE"
    - name: Commit Report
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add hunt-reports/
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update threat hunt report for issue #${{ github.event.issue.number }}: ${{ github.event.issue.title }}"
          git push
        fi
