name: Update Threat Hunt Report

on:
  issue_comment:
    types: [edited]

permissions:
  issues: read
  contents: write
  pull-requests: write

jobs:
  update-report: 
    runs-on: ubuntu-latest
    env:
      COMMENT_BODY: ${{ github.event.comment.body }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Update Report
      run: |
        FILE_NAME="hunt-reports/hunt-report-2025-08-09-2-this-is-a-test.md"

        FIRST_LINE=$(echo "$COMMENT_BODY" | head -n 1)
        LAST_LINE=$(echo "$COMMENT_BODY" | tail -n 1)
        MIDDLE_LINES=$(echo "$COMMENT_BODY" | sed '1d;$d')
        
        # Save middle lines to a temp file
        TMP_MIDDLE=$(mktemp)
        echo "$MIDDLE_LINES" > "$TMP_MIDDLE"
        awk -v start="$FIRST_LINE" -v end="$LAST_LINE" -v middlefile="$TMP_MIDDLE" '
          $0 == start { 
              print; 
              while ((getline line < middlefile) > 0) print line; 
              skip=1; 
              next 
          }
          $0 == end { skip=0; print; next }
          !skip { print }
        ' "$FILE_NAME" > "$FILE_NAME.tmp" && mv "$FILE_NAME.tmp" "$FILE_NAME"
        
        rm "$TMP_MIDDLE"
              
    - uses: stefanzweifel/git-auto-commit-action@v6
